[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn backend_server:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"